### ISSUE TITLE
Fix highscore list in HTML

### ISSUE THREAD

**Issue by ChLah** [Super-Repair-Bros/Super-Repair-Bros.#12]
When using HTML version no highscores are shown

**Comment by ChLah** [comment]
Ok, I think I found the problem by just looking at Chrome's developer console.
When getting the highscores, the following error appears:
index.js:7 Mixed Content: The page at 'https://superrepairbros.de/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dreamlo.com/lb/5e37f0b3fe232612b8eac82f/json-desc'. This request has been blocked; the content must be served over HTTPS.
It seems, dreamlo does not support HTTPS...
@all : Any ideas about that? Disabling highscores in the HTML version would be a shame!

**Comment by ChLah** [comment]
Lessons learned:
Dreamlo has a valid certificate but for *.gear.host, so I just tried https://dreamlo.gear.host and this works!!
But unfortunately, you have to enable HTTPS via a donation of at least 5$ on your leaderboard to use this url :(

**Comment by ThomasChr** [comment]
I've donated those 5$ and told him to activate SSL for us. So let's hold tight...

**Comment by ThomasChr** [comment]
Still no answer from him.
I'll set up an Apache Server (on tcv8.de) which will forward all Requests from https to dreamlo in http meanwhile. That should gab the time until dreamlo will grant us https Access.
