### ISSUE TITLE
Add note for user that highscore date is in US timezone

### ISSUE THREAD

**Issue by ChLah** [Super-Repair-Bros/Super-Repair-Bros.#19]
Since Godot does not provide the possibility to get the user's timezone we have to show the original (US) time.
But we should at least show the user, that it's not his current timezone but US and thereby has offset.
Maybe as a small label in the highscore scene.

**Comment by ThomasChr** [comment]
Would‘t it be better to have a crude function just adding 1 to the hour and two while it‘s DST? It must not be exactly know when DST starts, just having sommer months and winter months are enough.
Or, of course, we roll our own free Firebase Database for our Highscores. @ChLah I heard you know how to do that?

**Comment by ThomasChr** [comment]
PS: I would guess the time is always in UTC

**Comment by ChLah** [comment]
@ThomasChr Not a big fan of firebase for such small projects.. The framework is just too complex and imo over the top for just storing highscores...
Just naively adding 1 or 2 hours is not sufficient enough, I guess. What about our international fans out there? 
Maybe just not showing the date is better?!
