### ISSUE TITLE
Redirect to highscore table when submitting your score

### ISSUE THREAD

**Issue by ChLah** [Super-Repair-Bros/Super-Repair-Bros.#22]
Instead of the menu scene, I think we should redirect to the highscore scene, when you submit your score. So you can instantly see, how you compete with others and gain motivation to play again!

**Comment by PyDario** [comment]
gonna read into Singletons later, to store global information

**Comment by ChLah** [comment]
No singletons needed. Just redirect to HighScore scene after request completed...

**Comment by PyDario** [comment]
I ran into an issue while redirecting to the Highscore scene
![image](https://user-images.githubusercontent.com/56290011/74106194-c7da3280-4b64-11ea-81db-89963d438e98.png)
Appearently he doesn't even go into the function "_on_HTTPRequest_request_completed"
I'm not sure what's causing this. The one thing i can imagine, is that the request to send the score and then calling the scores are too close together.

**Comment by ChLah** [comment]
The problem was the scene was still paused...
