### ISSUE TITLE
Submit highscores upper case

### ISSUE THREAD

**Issue by ChLah** [Super-Repair-Bros/Super-Repair-Bros.#24]
Since you can anyway just add your initials and even show it in upper case, we should also submit it in uppercase.
Otherwise "cl" "CL", "cL" and "Cl" look the same but are 4 different score entries.

**Comment by ThomasChr** [comment]
Good catch. Yes, submitting everything in uppercase is a good idea!
Godot provides STRING.to_upper() for that.
