### ISSUE TITLE
Crash sound plays on new game

### ISSUE THREAD

**Issue by PyDario** [Super-Repair-Bros/Super-Repair-Bros.#26]
As the title says. Upon starting a new game, the audio line for a crash is played

**Comment by ThomasChr** [comment]
Invalid does mean the Issue is not a valid problem, do you really mean that?
Then you can close it!

**Comment by EduardBaer** [comment]
The sound is played whenever a broken car appears on the map. It's expected to be played for the first broken car as well, isn't it?

**Comment by PyDario** [comment]
Yeah I noticed it now too. Felt weird at first when I started up the game. Issue closed.
