### ISSUE TITLE
Make Highscore saveable on dreamlo.com

### ISSUE THREAD

**Issue by ThomasChr** [Super-Repair-Bros/Super-Repair-Bros.#5]
http://dreamlo.com/ allows for simple highscore saving via http get.
So we need:
1. After the game ends you can input your name.
2. After inputting the name we're making a request to dreamlo.com to save it.
3. We do need an API Key, this Api Key should be inserted by the CI in the Source right before the build. So it's secret for everyone else apart us.

Okay, who feels up to it?
@burned42 Task 3 seems to have your name on it, do you know if this is possible?
@ChLah Can you find out how a API Request to deamlo.com works, simple on the command line? And post here how it's done?
@ThomasChr I can do part 2, if no one else would absolutely like to do it :-)

**Comment by ChLah** [comment]
I have already checked the page and received a private key alongside a public key.
This is not a real API key but just a part of the url.
With the private one you can submit scores, the public just has the right to read score(s).
@burned42 , is it possible to build a mechanism to replace a specific placeholder etc. in the code with a GitHub variable that is private for our team in CI? This way we could keep our private key secure.

Our public key is: 5e37f0b3fe232612b8eac82f ([xml](http://dreamlo.com/lb/5e37f0b3fe232612b8eac82f/xml) or [json](http://dreamlo.com/lb/5e37f0b3fe232612b8eac82f/json))

**Comment by ChLah** [comment]
Tasks would be:

- [X] Request credentials
- [x] Prepare CI for replacing the private key in code
- [x] Create scene for inputting highscore (and showing others)
- [x] Build HTTP GETs for getting highscores and submitting them

**Comment by burned42** [comment]
@ThomasChr @ChLah I guess that would be possible, yes. We already added some 'hidden secret' to travis which it uses to push to gitlab pages. It should be possible to also add this API key and replace some placeholder in our code.

**Comment by ThomasChr** [comment]
Prepared Branch highscore for this and trying to get some code in it. Hold tight!

**Comment by ThomasChr** [comment]
Branch highscore can show the highscore and send the highscore.
@entensee403 I need all Highscore Button Graphics similar to the Credits Button Graphics...
@burned42 You need to replace the code 

> $OURSECRETKEYHERE

in the build with our secret key!

@DDTyphos Would you mind making the gameover screen more beautiful? At the moment it works but the design sucks. It sucks hard!

@ChLah What do you think?

@EduardBaer @mychecknix If anyone of you would like to help or change the design (one of you made the gameover screen, or am I wrong?) just jump on in!

**Comment by ThomasChr** [comment]
@all I have removed the duplicate GameOver Scene in level.tscn, I simply removed the following code with the text editor:

> [node name="GameOver" parent="." instance=ExtResource( 12 )]

This code was in there two times. It seems to work just fine now...

**Comment by PyDario** [comment]
@ThomasChr I think the Game Over screen looks fine as it is. Not sure how I could improve upon it

**Comment by ThomasChr** [comment]
You looked at the right game over screen? The one with the save highscore button from the branch highscore?

**Comment by PyDario** [comment]
@ThomasChr I stretched the text a bit. That should do the trick.

**Comment by ThomasChr** [comment]
Looks good!
@entensee403 will draw the buttons, and if @burned42 can make the CI do it's magic we're done here!

**Comment by ThomasChr** [comment]
Buttons are drawn, included and pushed!
@burned42 Your turn :-)

**Comment by ThomasChr** [comment]
With the help of @ChLah we managed to get it going!
Nothing to do for you here anymore @burned42
